name: dwarves-build

on:
  pull_request:
  push:
  schedule:
    - cron:  '0 18 * * *'

concurrency:
  group: ci-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  debian:
    runs-on: ubuntu-latest
    name: Debian Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            target: RUN
          - name: gcc-12
            target: RUN_GCC12
          - name: clang
            target: RUN_CLANG
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: setup
        shell: bash
        run: ./.github/scripts/build-debian.sh SETUP ${{ matrix.target }}

